# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-29 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
