# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-29 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutepro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdata',
            name='dob',
        ),
    ]
