# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-30 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institutepro', '0002_remove_registrationdata_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('py', 'Pyhton'), ('dj', 'Django'), ('rapi', 'Rest api')], max_length=100)),
                ('startdate', models.DateField()),
                ('timings', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'evening')], max_length=100)),
            ],
        ),
    ]
