# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-30 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutepro', '0004_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('permalink', models.CharField(max_length=20, unique=True)),
                ('update_date', models.DateTimeField(verbose_name='last_updated')),
            ],
        ),
    ]
